---
# Source: mq-metric-samples/templates/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: mq-metric-samples
    app.kubernetes.io/instance: mq-metric-samples
  name: mq-metric-samples
spec:
  endpoints:
  - bearerTokenSecret:
      key: ''
    port: metrics
    scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/name: mq-metric-samples
      app.kubernetes.io/instance: mq-metric-samples
